"""Filesystem store — investigation state under a configurable data root.

Never hardcodes a project path. Base dir is:
  1. WIZARD_DATA_DIR env var, or
  2. <cwd>/.wizard  (relative to process cwd only as last resort)

All investigation artifacts live under {base}/investigations/{id}/.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any


def data_root() -> Path:
    raw = os.environ.get("WIZARD_DATA_DIR")
    if raw:
        root = Path(raw).expanduser().resolve()
    else:
        root = (Path.cwd() / ".wizard").resolve()
    root.mkdir(parents=True, exist_ok=True)
    return root


def inv_dir(inv_id: str) -> Path:
    # inv_id is generated by kernel (inv_hex) — still sanitize for safety
    safe = "".join(c for c in inv_id if c.isalnum() or c in ("_", "-"))
    if not safe:
        raise ValueError("invalid investigation id")
    return data_root() / "investigations" / safe


def ensure(inv_id: str) -> Path:
    d = inv_dir(inv_id)
    d.mkdir(parents=True, exist_ok=True)
    (d / "observations").mkdir(exist_ok=True)
    return d


def write(inv_id: str, filename: str, data: dict | list) -> Path:
    """Write JSON document (meta, graphs, claims, etc.)."""
    _assert_safe_filename(filename)
    p = ensure(inv_id) / filename
    p.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
    return p


def write_text(inv_id: str, filename: str, text: str) -> Path:
    """Write raw text (e.g. verification_report.md)."""
    _assert_safe_filename(filename)
    p = ensure(inv_id) / filename
    p.write_text(text, encoding="utf-8")
    return p


def read(inv_id: str, filename: str) -> dict | list | None:
    _assert_safe_filename(filename)
    p = inv_dir(inv_id) / filename
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def read_text(inv_id: str, filename: str) -> str | None:
    _assert_safe_filename(filename)
    p = inv_dir(inv_id) / filename
    if not p.exists():
        return None
    return p.read_text(encoding="utf-8")


def write_observation(inv_id: str, seq: int, data: dict[str, Any]) -> Path:
    p = ensure(inv_id) / "observations" / f"o_{seq:04d}.json"
    p.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
    return p


def report_path(inv_id: str) -> Path:
    return inv_dir(inv_id) / "verification_report.md"


def _assert_safe_filename(filename: str) -> None:
    name = Path(filename).name
    if name != filename or ".." in filename or "/" in filename or "\\" in filename:
        raise ValueError(f"unsafe storage filename: {filename!r}")
