"""Command handler: wizard report [options]

Orchestrates the complete 6-step CLI pipeline for the "report"
command family, as defined in cli.md:

    Step 1 -- Command Parsing:      Validate options (no target for report)
    Step 2 -- Intent Construction:   Build a typed Intent from parsed components
    Step 3 -- Request Assembly:      Package Intent + repo + options into InvestigationRequest
    Step 4 -- Runtime Communication: Send the request to the Runtime Engine
    Step 5 -- Progress Display:      Show report generation progress to the user
    Step 6 -- Result Display:        Render the response and save the report file

The report command generates the final Verification Report from the
current investigation's verified knowledge.

Report output behavior:
    - The Runtime Engine generates verification_report.md in its own directory.
    - For markdown format (--format markdown), the CLI duplicates the report
      into an output/ folder at the project root. This gives users a local
      copy without navigating the Runtime Engine's directory structure.
    - For json format (--format json), the report is written to the
      specified --output path (or printed to stdout).
    - The --output option allows specifying a custom output path.

This handler contains ZERO domain logic. It does not know what a
verification report contains or how it is generated. It only knows
how to request one from the Runtime Engine and where to save the result.
"""

from __future__ import annotations

from pathlib import Path

import typer

from wizard.cli.parser.intent_builder import build_intent
from wizard.cli.models.investigation_request import (
    InvestigationRequest,
    RepositoryInfo,
    RequestOptions,
)
from wizard.cli.runtime_client.client import send_request
from wizard.cli.display.progress import show_progress
from wizard.cli.display.results import show_results


def report(
    repo: str = typer.Option(
        ".",
        "--repo",
        "-r",
        help="Path to the repository.",
        show_default="current directory",
    ),
    output_format: str = typer.Option(
        "markdown",
        "--format",
        "-f",
        help="Output format: markdown or json.",
    ),
    output_path: str = typer.Option(
        "",
        "--output",
        "-o",
        help="Custom output file path. Defaults to output/verification_report.md",
        show_default=False,
    ),
    verbose: bool = typer.Option(
        False,
        "--verbose",
        help="Show detailed progress.",
    ),
    quiet: bool = typer.Option(
        False,
        "--quiet",
        "-q",
        help="Suppress all output except the final result.",
    ),
    budget: int = typer.Option(
        100,
        "--budget",
        "-b",
        help="Maximum number of tool executions allowed.",
        min=1,
    ),
) -> None:
    """Generate a Verification Report from verified knowledge.

    The report is generated by the Runtime Engine from the current
    investigation's verified knowledge. For markdown format, a copy
    is saved in the output/ directory at the project root.

    \b
    Examples:
        wizard report
        wizard report --format markdown
        wizard report --format json
        wizard report --output report.md
        wizard report --format json --output ./reports/result.json
        wizard report --repo /path/to/project --verbose
    """

    # -----------------------------------------------------------------------
    # Step 1: Command Parsing -- Validate options (report has no target)
    # -----------------------------------------------------------------------
    # Validate format option
    valid_formats = ("markdown", "json")
    if output_format not in valid_formats:
        typer.echo(
            f'Error: "{output_format}" is not a valid format.\n'
            f'Valid formats: {", ".join(valid_formats)}',
            err=True,
        )
        raise typer.Exit(code=1)

    # Validate that the repository path exists
    repo_path = Path(repo).resolve()
    if not repo_path.exists():
        typer.echo(
            f'Error: Repository path does not exist: {repo}\n'
            f'Specify a valid path with --repo or run Wizard from inside a repository.',
            err=True,
        )
        raise typer.Exit(code=1)

    if not repo_path.is_dir():
        typer.echo(
            f'Error: Not a directory: {repo}',
            err=True,
        )
        raise typer.Exit(code=1)

    # Resolve the output directory (always output/ at project root)
    output_dir = repo_path / "output"

    # -----------------------------------------------------------------------
    # Step 2: Intent Construction -- Build the Intent
    # -----------------------------------------------------------------------
    intent = build_intent(action="report", target=None)

    # -----------------------------------------------------------------------
    # Step 3: Investigation Request Assembly -- Package everything
    # -----------------------------------------------------------------------
    request = InvestigationRequest(
        repository=RepositoryInfo(
            path=str(repo_path),
            type="local",
        ),
        intent=intent,
        options=RequestOptions(
            budget=budget,
            output_format=output_format,
            verbose=verbose,
            quiet=quiet,
        ),
    )

    # -----------------------------------------------------------------------
    # Step 5: Progress Display -- Show what we're about to do
    # -----------------------------------------------------------------------
    show_progress(request)

    # -----------------------------------------------------------------------
    # Step 4: Runtime Engine Communication -- Send the request
    # -----------------------------------------------------------------------
    response = send_request(request)

    # -----------------------------------------------------------------------
    # Step 6: Result Display -- Show the response and save the report
    # -----------------------------------------------------------------------
    show_results(response, verbose=verbose)

    # Save the report file if the Runtime Engine returned report content.
    # The runtime client returns report content under "report_markdown".
    report_content = response.data.get("report_markdown")

    if report_content:
        # Determine the file extension based on format
        ext = ".json" if output_format == "json" else ".md"

        # Always save to output/ with auto-incrementing name
        output_report_path = _next_report_path(output_dir, ext)
        _save_report(output_report_path, report_content, quiet=quiet)

        # If --output was specified, also save a copy to the custom path
        if output_path:
            custom_path = Path(output_path).resolve()
            _save_report(custom_path, report_content, quiet=quiet)
    else:
        # Engine unavailable or no content returned
        ext = ".json" if output_format == "json" else ".md"
        expected_path = _next_report_path(output_dir, ext, dry_run=True)
        if not quiet:
            typer.echo(
                f"Report will be saved to: {expected_path}\n"
                f"(Runtime Engine not yet available -- no report content generated)"
            )


def _next_report_path(output_dir: Path, ext: str, *, dry_run: bool = False) -> Path:
    """Find the next available report filename in the output directory.

    Scans for existing verification_report(N) files and returns the
    next incremented path. Never overwrites.

    Args:
        output_dir: The output/ directory at the project root.
        ext: File extension (".md" or ".json").
        dry_run: If True, don't create the directory — just compute the path.

    Returns:
        Path like output/verification_report(1).md, output/verification_report(2).md, etc.
    """
    if not dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    # Find the highest existing report number
    highest = 0
    if output_dir.exists():
        for existing in output_dir.iterdir():
            name = existing.stem  # e.g. "verification_report(3)"
            if name.startswith("verification_report(") and name.endswith(")"):
                try:
                    num = int(name[len("verification_report("):-1])
                    highest = max(highest, num)
                except ValueError:
                    continue
            elif name == "verification_report" and existing.suffix == ext:
                # Count the unnumbered one as 0
                highest = max(highest, 0)

    next_num = highest + 1
    return output_dir / f"verification_report({next_num}){ext}"


def _save_report(output_path: Path, content: str, *, quiet: bool = False) -> None:
    """Save report content to the specified file path.

    Creates parent directories if they do not exist.

    Args:
        output_path: Absolute path to the output file.
        content: The report content to write.
        quiet: If True, suppress the save confirmation message.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    if not quiet:
        typer.echo(f"Report saved: {output_path}")

