"""Report generator — projects verified state into markdown.
Every claim traces to an observation via evidence. No LLM prose."""
from __future__ import annotations

from typing import TYPE_CHECKING
from wizard_kernel.session.investigation import Investigation
from wizard_kernel.belief import trust as trust_engine

if TYPE_CHECKING:
    from wizard_kernel.control.investigation_graph import InvestigationGraph
    from wizard_kernel.contracts.observation import Observation
    from wizard_kernel.belief.knowledge_graph import KnowledgeGraph


def generate(
    inv: Investigation,
    graph: "InvestigationGraph",
    observations: "list[Observation]",
    kg: "KnowledgeGraph | None" = None,
) -> str:
    budget_used = inv.budget_total - inv.budget_remaining
    lines: list[str] = [
        "# Verification Report",
        "",
        f"**Investigation ID:** `{inv.id}`  ",
        f"**Repository:** `{inv.repository_path}`  ",
        f"**Intent:** {inv.intent}  ",
        f"**Targets:** {', '.join(inv.targets) or 'none specified'}  ",
        f"**Budget used:** {budget_used} / {inv.budget_total} nodes  ",
        f"**Observations collected:** {len(observations)}  ",
        f"**Claims verified:** {kg.summary()['claims_count'] if kg else 0}  ",
        "",
        "---",
        "",
    ]

    # ── Knowledge Graph claims ─────────────────────────────────────────────────
    if kg:
        claims = kg.all_claims()
        if claims:
            lines += [
                "## Verified Claims",
                "",
                "| Claim Type | Key | Value | Trust | Execution Evidence |",
                "|---|---|---|---|---|",
            ]
            for claim in sorted(claims, key=lambda c: kg.trust_of(c.id), reverse=True):
                trust = kg.trust_of(claim.id)
                has_exec = "✅" if kg.has_execution_evidence(claim.id) else "❌"
                trust_bar = _trust_bar(trust)
                lines.append(
                    f"| `{claim.claim_type}` | `{claim.key}` | `{claim.value}` "
                    f"| {trust_bar} {trust:.2f} | {has_exec} |"
                )
            lines += [""]

        contradictions = [
            c for c in claims
            if trust_engine.disbelief(kg.evidence_for(c.id)) > 0.3
        ]
        if contradictions:
            lines += [
                "## ⚠️ Contradictions",
                "",
                "| Claim Type | Key | Belief | Disbelief |",
                "|---|---|---|---|",
            ]
            for c in contradictions:
                evs = kg.evidence_for(c.id)
                b = trust_engine.compute(evs)
                d = trust_engine.disbelief(evs)
                lines.append(f"| `{c.claim_type}` | `{c.key}` | {b:.2f} | {d:.2f} |")
            lines += [""]

    # ── Investigation graph ────────────────────────────────────────────────────
    lines += [
        "## Investigation Graph",
        "",
        "| Node | Type | State |",
        "|---|---|---|",
    ]
    for n in graph.all_nodes():
        lines.append(f"| `{n.id}` | {n.type} | {n.state} |")

    # ── Evidence trail ─────────────────────────────────────────────────────────
    lines += [
        "",
        "## Evidence Trail",
        "",
        "| Observation | Tool | Type | Node |",
        "|---|---|---|---|",
    ]
    for o in observations:
        lines.append(f"| `{o.id}` | {o.source_tool} | {o.obs_type} | `{o.node_id}` |")

    lines += [
        "",
        "---",
        "",
        "*Generated by Wizard Investigation Kernel v0.1.0*",
    ]
    return "\n".join(lines)


def _trust_bar(score: float) -> str:
    filled = round(score * 5)
    return "█" * filled + "░" * (5 - filled)
