"""Report generator — projects verified state into markdown. Phase 5.
Every claim cited must trace to an observation. No LLM for report prose."""
from __future__ import annotations

from typing import TYPE_CHECKING
from wizard_kernel.session.investigation import Investigation

if TYPE_CHECKING:
    from wizard_kernel.control.investigation_graph import InvestigationGraph
    from wizard_kernel.contracts.observation import Observation


def generate(
    inv: Investigation,
    graph: "InvestigationGraph",
    observations: "list[Observation]",
) -> str:
    obs_index = {o.id: o for o in observations}
    nodes_done = [n for n in graph.all_nodes() if n.state == "complete"]
    budget_used = inv.budget_total - inv.budget_remaining

    lines: list[str] = [
        f"# Verification Report",
        f"",
        f"**Investigation ID:** `{inv.id}`  ",
        f"**Repository:** `{inv.repository_path}`  ",
        f"**Intent:** {inv.intent}  ",
        f"**Targets:** {', '.join(inv.targets) or 'none specified'}  ",
        f"**Budget used:** {budget_used} / {inv.budget_total} nodes  ",
        f"**Observations collected:** {len(observations)}  ",
        f"",
        f"---",
        f"",
        f"## Investigation Graph Summary",
        f"",
        f"| Node | Type | State |",
        f"|---|---|---|",
    ]

    for n in graph.all_nodes():
        lines.append(f"| `{n.id}` | {n.type} | {n.state} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## Evidence Trail",
        f"",
        f"| Observation | Tool | Type | Node |",
        f"|---|---|---|---|",
    ]

    for o in observations:
        lines.append(f"| `{o.id}` | {o.source_tool} | {o.obs_type} | `{o.node_id}` |")

    lines += [
        f"",
        f"---",
        f"",
        f"## Notes",
        f"",
        f"This is a Phase 3/5 partial report. Full claim analysis added in Phase 4–5.",
        f"",
        f"*Generated by Wizard Investigation Kernel v0.1.0*",
    ]

    return "\n".join(lines)
