"""SandboxRuntime protocol — all runtimes implement this interface."""
from typing import Protocol, runtime_checkable
from wizard_kernel.contracts.tool import CommandResult
from wizard_kernel.contracts.process import BackgroundProcess


@runtime_checkable
class SandboxRuntime(Protocol):
    # ── Lifecycle ─────────────────────────────────────────────────────────────
    def start(self, workspace_path: str) -> None: ...
    def stop(self) -> None: ...

    # ── Blocking execution (for commands that terminate) ──────────────────────
    def exec(self, command: str, cwd: str, timeout_sec: int) -> CommandResult: ...

    # ── File access ───────────────────────────────────────────────────────────
    def read_file(self, path: str, max_bytes: int) -> bytes: ...

    # ── Background process management (for long-running servers/apps) ─────────
    def exec_background(self, command: str, cwd: str) -> BackgroundProcess: ...
    def read_process_output(self, handle_id: str) -> BackgroundProcess: ...
    def kill_process(self, handle_id: str) -> None: ...
    def list_processes(self) -> list[BackgroundProcess]: ...
