"""SandboxRuntime protocol — all runtimes implement this. Phase 2."""
from typing import Protocol, runtime_checkable
from wizard_kernel.contracts.tool import CommandResult


@runtime_checkable
class SandboxRuntime(Protocol):
    def start(self, workspace_path: str) -> None: ...
    def exec(self, command: str, cwd: str, timeout_sec: int) -> CommandResult: ...
    def read_file(self, path: str, max_bytes: int) -> bytes: ...
    def stop(self) -> None: ...
